{{ if .Values.auth.enabled }}
{{ if not .Values.auth.saslPassword }}
{{ $provider := "" }}
{{ if .Values.auth.gcp }}
{{ $provider = "gcp" }}
{{ if .Values.auth.aws }}
{{ $provider = "aws" }}
{{ else if .Values.auth.vault }}
{{ $provider = "vault" }}
{{ end }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  {{- if .Values.auth.secretProviderClassName }}
  name: {{ .Values.auth.secretProviderClassName }}
  {{- else }}
  name: {{ .Release.Name }}-kafka-producer
  {{ end }}
spec:
  provider: {{ $provider }}
  {{- if .Values.auth.secrets.useOpaqueSecrets}}
  secretObjects:
  - secretName: {{ .Release.Name }}-kafka-producer
    type: Opaque
    data:
    - objectName: SASL_PASSWORD
      key: SASL_PASSWORD
    {{- if .Values.auth.secrets.useTruststore }}
    - objectName: TRUSTSTORE_PASSWORD
      key: TRUSTSTORE_PASSWORD
    {{- end}}
  {{- end}}
{{- if eq $provider "gcp"}}
  parameters:
    secrets: >
      - resourceName: "{{ .Values.auth.gcp.saslPasswordResource }}"
        fileName: "SASL_PASSWORD"
      {{- if .Values.auth.secrets.useTruststore }}
      - resourceName: "{{ .Values.auth.gcp.truststore.truststoreResource }}"
        fileName: "TRUSTSTORE"
      - resourceName: "{{ .Values.auth.gcp.truststore.truststorePasswordResource }}"
        fileName: "TRUSTSTORE_PASSWORD"
      {{- end}}
{{- end}}
{{- if eq $provider "aws"}}
  parameters:
    objects: |
        - objectName: {{ .Values.auth.aws.objectName }}
          objectType: secretsmanager
          jmesPath: 
            - path: {{ .Values.auth.aws.saslPasswordPath }}
              objectAlias: SASL_PASSWORD
            {{- if .Values.auth.secrets.useTruststore }}
            - path: {{ .Values.auth.aws.truststorePath }}
              objectAlias: TRUSTSTORE
            - path: {{ .Values.auth.aws.truststorePasswordPath }}
              objectAlias: TRUSTSTORE_PASSWORD
            {{- end}}
{{- end}}
{{- if eq $provider "vault"}}
  parameters:
    roleName: {{ .Values.auth.vault.roleName }}
    objects: >
      - secretPath: "{{ .Values.auth.vault.saslPasswordSecretPath }}"
        secretKey: "{{ .Values.auth.vault.saslPasswordSecretKey }}"
        objectName: "SASL_PASSWORD"
      {{- if .Values.auth.secrets.useTruststore }}
      - secretPath: "{{ .Values.auth.vault.truststoreSecretPath }}"
        secretKey: "{{ .Values.auth.vault.truststoreSecretKey }}"
        objectName: "TRUSTSTORE"
      - secretPath: "{{ .Values.auth.vault.truststorePasswordSecretPath }}"
        secretKey: "{{ .Values.auth.vault.truststorePasswordSecretKey }}"
        objectName: "TRUSTSTORE_PASSWORD"
      {{- end}}
{{- end}}
{{- end}}
{{ end }}
