# -- name for this producer
name: kafka-producer
# -- the port to use
port: &port 3000
# -- pod count
replicaCount: 1

# -- the url of the kafka broker
broker:

# -- the annotations to add to the deployment
deploymentAnnotations:

# -- Batch processing config https://www.conduktor.io/kafka/kafka-producer-batching/
lingerTimeMs:

# -- Batch processing config https://www.conduktor.io/kafka/kafka-producer-batching/
batchSize:

image:
  # -- the image name to use
  name: osskit/dafka-producer
  # -- the image tag to use
  tag: "7.2"

livenessProbe:
  initialDelaySeconds: 60

resources:
  requests:
    # -- cpu requests
    cpu: "50m"
    # -- memory requests
    memory: "100Mi"
  limits:
    # -- memory limits
    memory: "400Mi"

metrics:
  # -- should prometheus scrape this server
  enabled: true
  # -- a path prometheus should scrape metrics from
  path: /metrics

# -- how long a producer should wait for an ack from Kafka in MS (default: 60 seconds)
maxBlockMS:

auth:
  # -- should use authentication
  enabled: false
  # -- sasl username
  saslUsername:
  # -- sasl mechanism (PLAIN or SCRAM)
  saslMechanism: PLAIN
  # -- sasl password (not encrypted)
  saslPassword:
  secrets:
    # -- should mount secrets to opaque secrets
    useOpaqueSecrets: true
    # -- should use truststore
    useTrustsore: false
    gcp:
      # -- gcp secret resource for sasl password
      saslPasswordResource:
      # -- gcp secret resource for truststore file
      truststoreResource:
      # -- gcp secret resource for truststore password
      truststorePasswordResource:
    aws:
      # -- aws secret object name for sasl password
      saslPasswordObjectName:
      # -- aws secret object name for truststore
      saslTruststoreObjectName:
      # -- aws secret object name for truststore password
      saslTruststorePasswordObjectName:
    vault:
      # -- vault secret path for sasl password
      saslPasswordSecretPath:
      # -- vault secret key for sasl password
      saslPasswordSecretKey:
      # -- vault secret path for truststore file
      truststoreSecretPath:
      # -- vault secret key for truststore file
      truststoreSecretKey:
      # -- vault secret path for truststore password
      truststorePasswordSecretPath:
      # -- vault secret key for truststore password
      truststorePasswordSecretKey:

# -- Keda [ScaledObject](https://keda.sh/docs/2.8/concepts/scaling-deployments/) configuration
kedaScaledObject:
  # -- set to enabel scaled object support
  enabled: false
  # -- set to enable CPU based scaler
  cpu:
    enabled: false
  # -- set to enable Memor based scaler
  memory:
    enabled: false
  # -- set to enable Prometheus based scaler
  prometheus:
    enabled: false
  # -- set to enable Workload based scaler
  workload:
    enabled: false

# -- [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.serviceMonitor) configuration
serviceMonitor:
  # -- set to enable service monitor support
  enabled: false
  # -- set labels for the service monitor
  labels:
  # -- set sample limit for the service monitor
  sampleLimit:

pdb:
  # -- Set to true to enable
  enabled: true

# -- Rediness settings
readinessProbe:
  # -- How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
  periodSeconds: 10

jvmOpts:
