# -- name for this producer
name: kafka-producer
# -- the port to use
port: &port 3000
# -- pod count
replicaCount: 1

# -- the url of the kafka broker
broker: 

image:
  # -- the image name to use
  name: osskit/dafka-producer
  # -- the image tag to use
  tag: '5.0'

livenessProbe:
  initialDelaySeconds: 60

resources:
  requests:
    # -- cpu requests
    cpu: '50m'
    # -- memory requests
    memory: '100Mi'
  limits:
    # -- cpu limits
    cpu: '200m'
    # -- memory limits
    memory: '400Mi'

metrics:
  # -- should prometheus scrape this server
  enabled: true
  # -- a path prometheus should scrape metrics from
  path: /metrics

auth:
  # -- should use authentication
  enabled: false
  # -- sasl username
  saslUsername:
  # -- sasl mechanism (plain or scram)
  saslMechanism: PLAIN
  # -- sasl password (not encrypted)
  saslPassword:
  secrets:
    # -- should mount secrets to opaque secrets
    useOpaqueSecrets: true
    # -- should use truststore
    useTrustsore: false
    gcp:
      # -- gcp secret resource for sasl password
      saslPasswordResource:
      # -- gcp secret resource for truststore file
      truststoreResource:
      # -- gcp secret resource for truststore password
      truststorePasswordResource:
    aws:
      # -- aws objectName in secret manager (should be json object)
      objectName:
      # -- path in the secret manager object for the sasl password
      saslPasswordPath:
      # -- path in the secret manager object for truststore
      truststorePath:
      # -- path in the secret manager object for truststore password
      truststorePasswordPath:        
    vault:
      # -- vault secret path for sasl password
      saslPasswordSecretPath:
      # -- vault secret key for sasl password
      saslPasswordSecretKey:
      # -- vault secret path for truststore file
      truststoreSecretPath:
      # -- vault secret key for truststore file
      truststoreSecretKey:
      # -- vault secret path for truststore password
      truststorePasswordSecretPath:
      # -- vault secret key for truststore password
      truststorePasswordSecretKey:
