apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: {{ .Values.replicaCount }}
  selector:
      matchLabels:
        app: {{ .Release.Name }}-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.name }}
      annotations:
        prometheus.io/path: {{ .Values.metrics.path }}
        prometheus.io/port: {{ .Values.port | quote }}
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          volumeMounts:
            - name: kafka-secrets-volume
              mountPath: /secrets-files
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: PORT
              value: {{ .Values.port | squote }}  
            - name: KAFKA_BROKER
              value: {{ .Values.broker }}
            {{- if .Values.readinessTopic }}
            - name: READINESS_TOPIC
              value: {{ .Values.readinessTopic }}
            {{- end }}
            - name: USE_PROMETHEUS
              value: {{ .Values.metrics.enabled | squote }}
            - name: MONITORING_SERVER_PORT
              value: {{ .Values.port | squote }}        
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: SASL_USERNAME
              value: {{ .Values.auth.saslUsername | squote }}        
            - name: SASL_PASSWORD_FILE_PATH
              value: {{ .Values.auth.saslPasswordFilePath| squote }}
            {{- if and (.Values.auth.truststoreFilePath) (.Values.auth.truststorePasswordFilePath) }}
            - name: TRUSTSTORE_FILE_PATH
              value: {{ .Values.auth.truststoreFilePath | squote }} 
            - name: TRUSTSTORE_PASSWORD_FILE_PATH
              value: {{ .Values.auth.truststorePasswordFilePath | squote }} 
            {{- end }}         
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheckPath | squote }}
              port: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheckPath | squote }}
              port: {{ .Values.port }}       
          resources:
{{ toYaml .Values.resources | indent 12 }}      
      volumes:
        - name: kafka-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-kafka-producer