{{ if .Values.auth.saslPassword }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kafka-producer
spec:
  provider: gcp
  {{- if .Values.auth.useOpaqueSecrets}}
  secretObjects:
  - secretName: {{ .Release.Name }}-kafka-producer
    type: Opaque
    data: 
    - objectName: SASL_PASSWORD
      key: SASL_PASSWORD
    {{- if .Values.auth.truststore }}
    - objectName: TRUSTSTORE_PASSWORD
      key: TRUSTSTORE_PASSWORD
    {{- end}}
  {{- end}}
  parameters:
    secrets: >
      - resourceName: "{{ .Values.auth.saslPasswordResource }}"
        fileName: "SASL_PASSWORD"
      {{- if .Values.auth.truststore }}
      - resourceName: "{{ .Values.auth.truststore.truststoreResource }}"
        fileName: "TRUSTSTORE"
      - resourceName: "{{ .Values.auth.truststore.truststorePasswordResource }}"
        fileName: "TRUSTSTORE_PASSWORD"        
      {{- end}}
{{ end }}
